# Generated by Django 3.2.3 on 2021-05-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TIS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='localisation',
            new_name='location',
        ),
    ]
