# Generated by Django 3.1.6 on 2021-02-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('id_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.species')),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.IntegerField()),
                ('roloff', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('hollow', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.species')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.variant')),
            ],
        ),
    ]
