# Generated by Django 3.1.6 on 2021-02-18 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(500)])),
                ('roloff', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('hollow', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.species')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.variant')),
            ],
        ),
        migrations.DeleteModel(
            name='Trees',
        ),
    ]
