# Generated by Django 3.1.6 on 2021-02-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20210218_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='trees.species'),
        ),
    ]
